# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
  highlighter: rouge

# The GitHub Pages gem ignores all plugins included in the Gemfile. If you only include plugin in the Gemfile without also including it in the _config.yml the plugin will not work.
plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "Building meumobi: SaaS Platform for Mobile Projects"


title: "meumobi Dev Blog"
description: "Sharing Experience about Mobile Development with Ionic, Cordova, Angular and REST API"
author:
  name: meumobi
  email: contact@meumobi.com
  github: meumobi
  twitter: meumobi
  bio: Sharing mobile Experience @Rio_br, @Oporto_pt, @Paris_fr. Contact us for projects #Firebase #Angular #Ionic
  email_md5: 1cd012be2382e755aa763c66acc7cfa6

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# uncomment following line if used on gh-pages branch of git repository infoMobi
#BASE_PATH: /infoMobi

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: meumobi-dev

# Google Analytics
ga:
  id: UA-22519238-8

# the base hostname & protocol for jekyll-sitemap
url: https://meumobi.github.io
